### ISSUE TITLE
Executing main script taking too long

### ISSUE THREAD

**Issue by niizam** [O-Isaac/FGO-VerCode-extractor#2]
Please take a look at your Actions too, it's takes hours to extract the ver code https://github.com/O-Isaac/FGO-VerCode-extractor/actions/runs/4285997306

Anyways, here's the log
```
Run python3 main.py
I: Using Apktool 2.6.1 on fate.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: C:\Users\runneradmin\AppData\Local\apktool\framework\1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
Need update!
Traceback (most recent call last):
  File "D:\a\FGO-VerCode-extractor\FGO-VerCode-extractor\main.py", line 11, in <module>
[App] Creating folder...
[App] Downloading latest apk...!
[App] Apk downloaded!
[App] Decompiling apk...
[App] Decrypting Files!
    decrypt()
  File "D:\a\FGO-VerCode-extractor\FGO-VerCode-extractor\libs\python\decompile.py", line 23, in decrypt
    p.communicate(input=b'\n')
  File "C:\hostedtoolcache\windows\Python\3.9.13\x6[4](https://github.com/niizam/FGO-VerCode-extractor/actions/runs/4281396565/jobs/7468316496#step:4:5)\lib\subprocess.py", line 1134, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\subprocess.py", line 1[5](https://github.com/niizam/FGO-VerCode-extractor/actions/runs/4281396565/jobs/7468316496#step:4:6)08, in _communicate
    self.stdout_thread.join(self._remaining_time(endtime))
  File "C:\hostedtoolcache\windows\Python\3.9.13\x[6](https://github.com/niizam/FGO-VerCode-extractor/actions/runs/4281396565/jobs/7468316496#step:4:7)4\lib\threading.py", line 1060, in join
    self._wait_for_tstate_lock()
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\threading.py", line 10[8](https://github.com/niizam/FGO-VerCode-extractor/actions/runs/4281396565/jobs/7468316496#step:4:9)0, in _wait_for_tstate_lock
    if lock.acquire(block, timeout):
KeyboardInterrupt
Error: The operation was canceled.
```

**Comment by O-Isaac** [comment]
| State | Enviroment 📦 |
|-------------|------------------|
| 🟢  Fixed | **Python** |

### Problem
When decrypt file on [libs.python.decompile](https://github.com/O-Isaac/FGO-VerCode-extractor/blob/fd4a009cfe4f741d01c15460ee5273b9212db227/libs/python/decompile.py#L18) have the problem sometime **apk** dont have lib **arm64-v8a*** or **armeabi-v7a**

### Fix
Create function to detect Libs and use the first lib folder detected.

**Comment by O-Isaac** [comment]
This error has been fixed!
